version: '3.7'
networks:
  backend_tier:
    external: true
  frontend_tier:
    external: true
services:
  postgres:
    image: postgres
    container_name: ${POSTGRES_CONTAINER_NAME}
    networks:
      backend_tier:
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DEFAULT_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_USER_PASSWORD}
    volumes:
      - ../../Volume/${POSTGRES_DIR}:/var/lib/postgresql
    restart: always