version: "3.7"
networks:
  back_tier:
    name: back_tier
    driver: bridge
  front_tier:
    name: front_tier
    driver: bridge
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /Dockerized-Environment-Boilerplate/Volume/Nginx-Proxy-SSL/conf.d:/etc/nginx/conf.d
      - /Dockerized-Environment-Boilerplate/Volume/Nginx-Proxy-SSL/vhost.d:/etc/nginx/vhost.d
      - /Dockerized-Environment-Boilerplate/Volume/Nginx-Proxy-SSL/html:/usr/share/nginx/html
      - /Dockerized-Environment-Boilerplate/Volume/Nginx-Proxy-SSL/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - back_tier
      - front_tier
    restart: always
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: encrypt
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /Dockerized-Environment-Boilerplate/Volume/Nginx-Proxy-SSL/certs:/etc/nginx/certs:rw
      - /Dockerized-Environment-Boilerplate/Volume/Nginx-Proxy-SSL/conf.d:/etc/nginx/conf.d
      - /Dockerized-Environment-Boilerplate/Volume/Nginx-Proxy-SSL/vhost.d:/etc/nginx/vhost.d
      - /Dockerized-Environment-Boilerplate/Volume/Nginx-Proxy-SSL/html:/usr/share/nginx/html
    networks:
      - back_tier
    restart: always
  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:
      - /Dockerized-Environment-Boilerplate/Volume/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rawaf
      MYSQL_USER: rawaf
      MYSQL_PASSWORD: rawaf
    networks:
      back_tier:
    restart: always