version: '3.7'
networks:
  backend_tier:
    external: true
  frontend_tier:
    external: true
services:
  php-fpm:
    build: ../PHP-FPM
    image: ${PHP_FPM_IMAGE_NAME}
    container_name: ${PHP_FPM_CONTAINER_NAME}
    networks:
      backend_tier:
    external_links:
      - ${DATABASE_CONTAINER_NAME}
    volumes:
      - ../../Volume/${APP_NAME}/www:/var/www/html
  nginx:
    image: nginx
    container_name: ${NGINX_CONTAINER_NAME}
    depends_on:
      - php-fpm
    volumes:
      - ../../Volume/${APP_NAME}/conf.d:/etc/nginx/conf.d
      - ../../Volume/${APP_NAME}/www:/var/www/html
      - ../../Volume/${APP_NAME}/log/nginx:/var/log/nginx
    expose:
      - 80
      - 443
    networks:
      backend_tier:
      frontend_tier:
    environment:
      VIRTUAL_PORT: 443
      VIRTUAL_HOST: ${APP_DOMAIN},www.${APP_DOMAIN}
      LETSENCRYPT_HOST: ${APP_DOMAIN},www.${APP_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    restart: always
