version: '3.7'
networks:
  back_tier:
    external: true
  front_tier:
    external: true
services:
  php-fpm:
    build:
      context: /Dockerized-Environment-Boilerplate/Hub/Wamvo/PHP-FPM
    container_name: php-wamvo
    volumes:
      - /Dockerized-Environment-Boilerplate/Volume/Wamvo/www:/var/www/html
    networks:
      back_tier:
  nginx:
    image: nginx
    container_name: nginx-wamvo
    depends_on:
      - php-fpm
    volumes:
      - /Dockerized-Environment-Boilerplate/Volume/Wamvo/conf.d:/etc/nginx/conf.d
      - /Dockerized-Environment-Boilerplate/Volume/Wamvo/www:/var/www/html
      - /Dockerized-Environment-Boilerplate/Volume/Wamvo/log/nginx:/var/log/nginx
    ports:
      - 80
      - 443
    expose:
      - 80
    networks:
      back_tier:
      front_tier:
    environment:
      VIRTUAL_PROTO: https
      VIRTUAL_PORT: 443
      CERT_NAME: default
      VIRTUAL_HOST: wamvo.com
      LETSENCRYPT_HOST: wamvo.com
      LETSENCRYPT_EMAIL: contact@wamvo.com
    links:
      - php-fpm
    working_dir: /var/www/html
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    volumes:
      - /Dockerized-Environment-Boilerplate/Volume/phpmyadmin
    environment:
      VIRTUAL_HOST: phpmyadmin.wamvo.com
      PMA_DB_ENGINE: mariadb
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: https://phpmyadmin.wamvo.com
    ports:
      - 4001:4001
    external_links:
      - mariadb
    networks:
      back_tier:
    restart: always
