version: '3.7'
networks:
  back_tier:
    external: true
  front_tier:
    external: true
services:
  php-fpm:
    build:
      context: /Dockerized-Environment-Boilerplate/Hub/Project-Realestate-Eg/PHP-FPM
    container_name: php-project-realestate-eg
    volumes:
      - /Dockerized-Environment-Boilerplate/Volume/Project-Realestate-Eg/www:/var/www/html
    networks:
      back_tier:
    external_links:
      - mariadb
  nginx:
    image: nginx
    container_name: nginx-project-realestate-eg
    depends_on:
      - php-fpm
    volumes:
      - /Dockerized-Environment-Boilerplate/Volume/Project-Realestate-Eg/conf.d:/etc/nginx/conf.d
      - /Dockerized-Environment-Boilerplate/Volume/Project-Realestate-Eg/www:/var/www/html
      - /Dockerized-Environment-Boilerplate/Volume/Project-Realestate-Eg/log/nginx:/var/log/nginx
    expose:
      - 80
      - 443
    networks:
      back_tier:
      front_tier:
    environment:
      VIRTUAL_PORT: 443
      CERT_NAME: project-realestate-eg.com
      VIRTUAL_HOST: project-realestate-eg.com
      LETSENCRYPT_HOST: project-realestate-eg.com
      LETSENCRYPT_EMAIL: contact@project-realestate-eg.com
    links:
      - php-fpm
    external_links:
      - mariadb
    working_dir: /var/www/html
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-project-realestate-eg
    volumes:
      - /Dockerized-Environment-Boilerplate/Volume/Project-Realestate-Eg/phpmyadmin/phpmyadmin:/etc/phpmyadmin
    networks:
      back_tier:
    ports:
      - 8003:80
    environment:
      VIRTUAL_HOST: phpmyadmin.project-realestate-eg.com
      VIRTUAL_PORT: 8003
      PMA_DB_ENGINE: mariadb
      PMA_HOST: mariadb
    links:
      - php-fpm
    external_links:
      - mariadb
    restart: always
