version: "3.7"
networks:
  backend_tier:
    name: backend_tier
    driver: bridge
  frontend_tier:
    name: frontend_tier
    driver: bridge
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: ${NGINX_PROXY_CONTAINER_NAME}
    networks:
      - backend_tier
      - frontend_tier
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../../Volume/${NGINX_PROXY_LETS_ENCRYPT_DIR}/conf.d:/etc/nginx/conf.d
      - ../../Volume/${NGINX_PROXY_LETS_ENCRYPT_DIR}/vhost.d:/etc/nginx/vhost.d
      - ../../Volume/${NGINX_PROXY_LETS_ENCRYPT_DIR}/html:/usr/share/nginx/html
      - ../../Volume/${NGINX_PROXY_LETS_ENCRYPT_DIR}/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  letsEncrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ${LETS_ENCRYPT_CONTAINER_NAME}
    depends_on:
      - nginx-proxy
    networks:
      - backend_tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../../Volume/${NGINX_PROXY_LETS_ENCRYPT_DIR}/certs:/etc/nginx/certs:rw
      - ../../Volume/${NGINX_PROXY_LETS_ENCRYPT_DIR}/conf.d:/etc/nginx/conf.d
      - ../../Volume/${NGINX_PROXY_LETS_ENCRYPT_DIR}/vhost.d:/etc/nginx/vhost.d
      - ../../Volume/${NGINX_PROXY_LETS_ENCRYPT_DIR}/html:/usr/share/nginx/html
    restart: always
  netdata:
    image: netdata/netdata
    container_name: ${NETDATA_CONTAINER_NAME}
    networks:
      frontend_tier:
    ports:
      - ${NETDATA_HOST_PORT}:${NETDATA_CONTAINER_PORT}
    depends_on:
      - nginx-proxy
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    environment:
      PGID: ${DOCKER_GROUP_ID}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always